config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  get 'blog/index'

  get 'tiny_projects/index'

  get 'tiny_projects/about_me'

  get 'portfolio/index'

  get 'portfolio/create'

  get 'portfolio/epoch'

  get 'portfolio/mindkit'

  get 'site/index'

  get 'site/about'

  get 'site/cv'

  get 'site/contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index_show
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def about
  end

  def cv
  end

  def contact
  end
end

app/controllers/tiny_projects_controller.rb
class TinyProjectsController < ApplicationController
  def index
  end

  def about_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tiny_projects_helper.rb
module TinyProjectsHelper
end

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/blog/show.html.erb
<h1>Blog#show</h1>
<p>Find me in app/views/blog/show.html.erb</p>

app/views/layouts/_footer.html.erb
<!-- <div id="footer">
  <div class="container">
    <p class="text-muted">© Copyright 2015 Annie Pennell</p>
  </div>
</div> -->

<footer class="footer">
  <div class="container">
    <p class="text-muted">© Copyright 2015 Annie Pennell</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav role="navigation" class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand topnav" href="/">Annie Pennell</a>
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Portfolio", portfolio_index_path %></li>
      <li><%= link_to "Tiny Projects", tiny_projects_index_path %></li>
      <li><%= link_to "About", site_about_path %></li>
      <li><%= link_to "CV", site_cv_path %></li>
      <li><%= link_to "Contact", site_contact_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,100,200,600,700,800,900,500' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/portfolio/create.html.erb
<div class="container">
  <h1>Create</h1>

  <strong><a href="https://createtoday.herokuapp.com/">Visit App</a> | <a href="https://github.com/apennell/create_app">GitHub Repository</a></strong>
  <br>
  <p>Created April 2015</p>
  <br>
  <p>
    Create is a daily art prompt web app built with Node.js, Express, Postgres, and Bootstrap, integrating authentication and authorization. Utilizing Wordnik’s API, a new word appears every day to provide inspiration. Users, called creators, use the prompt to make something in response, which can be posted to the site. All posts ("creations") can be viewed publicly, as well users' public profiles.
  </p>
  <p>
    The MVP simply allows for a written creation (poem, short story, etc.), but the goal is to add an image upload option so that photographers and visual artists can contribute as well. It has authorization and authentication to allow users to post and delete creations. It currently has a one-to-many association with many creations belonging to one user, but I would like to add a prompt model.
  </p>
  <br><br>
  <div class="row">
    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'create/create1.png', :alt => 'Home Screenshot' %>
    </div>
    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'create/create2.png', :alt => 'Home Screenshot' %>
    </div>
    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'create/create3.png', :alt => 'Profile Screenshot' %>
    </div>
  </div>
  <br><br>
  <p>
    <strong>Create's future</strong>
  </p>
  <p>
    I would like to add image upload functionality to so that visual artists can contribute to Create's online community as well, as this was my initial vision for the app. Once this is completed, there will be a visual design overhaul to the site, displaying thumbnails for each contribution. Additionally, users will have a profile photo. After this, I want to implement the capability for users to "favorite" and follow other users. The final key function I hope to add is a prompt model to the database, which would automatically add the word of the day to the table daily, then add association to a creation and a specific prompt. After this is implemented, users will be able to browse and search creations by prompt.
  </p>
</div>

app/views/portfolio/epoch.html.erb
<div class="container">
  <h1>Epoch</h1>

  <strong><a href="https://github.com/apennell/timebank">GitHub Repository</a> | <a href="https://epochbank.herokuapp.com/">Visit App</a></strong>
  <br>
  <p>Created April 2015</p>
  <br>
  <p>
    Epoch is a time banking web app built with Ruby on Rails, utilizing AJAX, Bootstrap, Devise, and Twilio's API. Epoch was built by myself, James Bradley, Lyn Muldrow, and Steven Gordon. In addition to acting as project manager for three other engineers, my main tasks were authentication and authorization, constructing the User controller and views, and styling.
  </p>
  <p>
    Epoch allows users to receive services using the currency of their time, which is earned by providing other users with their own services. Every hour of work completed is removed from the recipient's account and added to the provider's, which can then be spent getting help from another user. Users sign up for the Epoch web app and act as both a provider and recipient. They list services they can provide as well as services they need. Users can offer to render a service wanted or request that a specific user help them. When a request is made, a text message alert is sent to the the user receiving the request. An exchange page is generated when a request is made and, once accepted, they receive each other's contact information. After service is rendered, this is confirmed on the site and the hour is transferred from the recipient to the provider's time bank. A text message alert is sent to the user at each of the 4 stages of the exchange process--when it is proposed, accepted, delivered, and confirmed. 
  </p>
  <div class="row">
    <div class="col-xs-12 col-md-6 thumbnail">
      <%= image_tag 'epoch/epoch1.png', :alt => 'Home Screenshot' %>
    </div>
    <div class="col-xs-12 col-md-6 thumbnail">
      <%= image_tag 'epoch/epoch2.png', :alt => 'Dashboard' %>
    </div>
    <div class="col-xs-12 col-md-6 thumbnail">
      <%= image_tag 'epoch/epoch3.png', :alt => 'Requests' %>
    </div>
    <div class="col-xs-12 col-md-6 thumbnail">
      <%= image_tag 'epoch/epoch4.png', :alt => 'Exchange' %>
    </div>
  </div>

  <br><br>

  <p>
    <strong>Epoch's future</strong>
  </p>
  <p>
    The main functionality we'd like to add, and were just on the cusp of finishing, is enable two way initiation of an exchange so that a user can request help from another whose profile lists the necessary skills. We would also like to add a search functionality so that a user can search for an view profiles and requests by category of service and location. 
  </p>
</div>

app/views/portfolio/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 port-index-header">
      <center><h1>portfolio projects</h1></center>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <h2><%= link_to "Create", portfolio_create_path(@create) %></h2>
      <strong>JavaScript, Node.js, Express, PostgreSQL, Wordnik API</strong>
      <br>
      <p>Daily art prompt community web app</p>
      <br>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2><%= link_to "Epoch", portfolio_epoch_path(@epoch) %></h2>
      <strong>Ruby on Rails, AJAX, Devise, Twilio API</strong>
      <br>
      <p>Time banking web app</p>
      <br><br>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2><%= link_to "MindKit", portfolio_mindkit_path(@mindkit) %></h2>
      <strong>Ionic, AngularJS, Node.js, Express, PostgreSQL</strong>
      <p>Depression management hybrid mobile app</p>
      <br>
    </div>
  </div>
</div>

app/views/portfolio/mindkit.html.erb
<div class="container">
  <h1>MindKit</h1>

  <strong><a href="https://github.com/apennell/mindKit">GitHub Repository</a></strong>
  <br>
  <p>Created June 2015</p>
  <br>
  <p>
    MindKit is a hybrid mobile app that acts as a toolkit for combating depression on a daily basis, largely through the use of cognitive behavioral therapy (CBT). It is built with Ionic using AngularJS and the database is connected with a NodeJS, Express, and PostgreSQL backend API. It is currently in beta in the Ionic View app, but once completed will be available for iOS and Android.
  </p>
  <p>
    The initial MVP is the thought log, in which Ionic-Wizard takes the user through a series of questions typical of a CBT automatic negative thought log to analyze a situation and their resulting thoughts and emotions. In the final step, the user is presented with their initial emotions and the strengths at which they reported feeling them and is asked to re-rate the emotions after going through the thought log. The differences between the initial and new emotions are averaged out and the user is shown the percentage of their improvement on this situation. They are also shown a lifetime improvement average and a graph of each entry's improvement on their progress page to see how the exercises are helping.
  </p>
  <br><br>
  <div class="row">
    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'mindkit/mindkit1.png', :alt => 'Home Screenshot' %>
    </div>

    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'mindkit/mindkit2.png', :alt => 'Thought Log Screenshot' %>
    </div>

    <div class="col-xs-12 col-md-4 thumbnail">
      <%= image_tag 'mindkit/mindkit3.png', :alt => 'Progress Screenshot' %>
    </div>
  </div>

  <br><br>
  
  <p>
    <strong>MindKit's future</strong>
    <br>
    There are many additional tools I plan to implement in this app. The first is a set of positive self-affirmations, displayed with Ionic's slide function. The user can add his/her own affirmations and swipe through them to improve self-image and self-talk. I would also like to add a quick daily check in and weekly goal-setting.
  </p>
</div>

app/views/site/about.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="well">
    <h3>A bit about me</h3>
    <p>
      After several years in New Orleans working as a <strong><a href="http://www.photography.anniepennell.com/">photographer</a></strong>, photo retoucher, and fine art print specialist, I returned to my roots in the Bay Area and am beginning a career as a full stack web developer. There are so many amazing companies here doing great things and I love the flexibility of industries the programmer skill set allows me to be a part of. I believe being a developer is the best way for me to make a positive contribution to the world.
      <br><br>
      I completed General Assembly's Web Development Immersive in June 2015, where I trained to be a full stack web developer. I am currently mastering JavaScript, Node.js, Ruby on Rails, and related frameworks and tools and am excited to take off on my new career path!
    </p>
  </div>
  <div>
    Still interested in learning more about me? Want to hear some nice things other people have to say? Curious about my early experiments with HTML, CSS, jQuery, and AJAX? Check out this <strong><a href="http://about-annie.divshot.io/">about me</a></strong> page that I made.
  </div>
  <br>
  <br>
  <div>
    <center>
      <a href="https://github.com/apennell"><i class="fa fa-github fa-2x"></i></a>
      &nbsp; &nbsp;
      <a href="https://www.linkedin.com/in/anniepennell"><i class="fa fa-linkedin fa-2x"></i></a>
      &nbsp; &nbsp;
      <a href="https://angel.co/annie-pennell"><i class="fa fa-angellist fa-2x"></i></a>
      &nbsp; &nbsp;
      <a href="http://photography.anniepennell.com/"><i class="fa fa-camera-retro fa-2x"></i></a>
    </center>
  </div>
</div>

app/views/site/contact.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="well">
    <center>
      <h3>Ready to hire me or just want to chat?</h3>
      <h4>Drop me a line!</h4>
      <h4>anniecpennell@gmail.com</h4>
      <br>
      <div>
        <center>
          <a href="https://github.com/apennell"><i class="fa fa-github fa-2x"></i></a>
          &nbsp; &nbsp;
          <a href="https://www.linkedin.com/in/anniepennell"><i class="fa fa-linkedin fa-2x"></i></a>
          &nbsp; &nbsp;
          <a href="https://angel.co/annie-pennell"><i class="fa fa-angellist fa-2x"></i></a>
          &nbsp; &nbsp;
          <a href="http://photography.anniepennell.com/"><i class="fa fa-camera-retro fa-2x"></i></a>
        </center>
      </div>
    </center>
  </div>
</div>

app/views/site/cv.html.erb
<div class="col-md-4 col-md-offset-1">
  <div class="panel panel-success">
    <div class="panel-body">
      <center>
        <a href="https://github.com/apennell"><i class="fa fa-github fa-2x"></i></a>
        &nbsp; &nbsp; &nbsp;
        <a href="https://www.linkedin.com/in/anniepennell"><i class="fa fa-linkedin fa-2x"></i></a>
        &nbsp; &nbsp; &nbsp;
        <a href="https://angel.co/annie-pennell"><i class="fa fa-angellist fa-2x"></i></a>
        &nbsp; &nbsp; &nbsp;
        <a href="http://photography.anniepennell.com/"><i class="fa fa-camera-retro fa-2x"></i></a>
      </center>
    </div>
  </div>

  <!-- skills panel -->
  <div class="panel panel-success">
    <div class="panel-heading">
      Skills
    </div>
    <div class="panel-body">
      <h4>Languages</h4>
      <p>
        JavaScript<br>
        Ruby<br>
        HTML<br>
        CSS<br>
      </p>
      <br>
      <h4>Frameworks</h4>
      <p>
        Node.js<br>
        Express.js<br>
        Rails<br>
        Angular<br>
      </p>
      <br>
      <h4>Database Tools</h4>
      <p>
        SQL<br>
        PostgreSL<br>
        Sequelize<br>
      </p>
      <br>
      <h4>Other</h4>
      <p>
        jQuery<br>
        AJAX<br>
        RSpec<br>
        Bootstrap<br>
        Git/GitHub<br>
        Heroku<br>
        Wordpress + Joomla<br>
        Adobe CS5 + 6
        Photography
      </p>
    </div>
  </div>

  <!-- education panel -->
  <div class="panel panel-success">
    <div class="panel-heading">
      Education
    </div>
    <div class="panel-body">
      <h4>General Assembly</h4>
      <p>
        <i>Web Development Immersive</i><br>
        March - June 2015
      </p>
      <br>
      <h4>Johnston Center for Integrative Studies, University of Redlands</h4>
      <p>
        <i>BA in Photography, Writing, + the Human Experience</i><br>
        2011<br>
      </p>
      <br>
      <h4>SIT World Learning, Study Abroad</h4>
      <p>
        <i>Morocco: Culture + Society</i><br>
        September - December 2009<br>
      </p>
    </div>
  </div>

  <!-- references panel -->
  <div class="panel panel-success">
    <div class="panel-heading">
      References
    </div>
    <div class="panel-body">
      <p>Want to hear nice things employers and professors have had to say about me in the past? Check out them out in this <strong><a href="http://about-annie.divshot.io/">about me</a></strong> page that I made.</p>
    </div>
  </div>
</div>

<!-- relevant experience panel -->
<div class="col-md-6">
  <div class="panel panel-success">
    <div class="panel-heading">
      Relevant Experience
    </div>
    <div class="panel-body">
      <h4>Student</h4>
      <h5>General Assembly Web Development Immersive | March to June 2015</h5>
      <p>
        Full time, 12-week full stack web development course building fluency in JavaScript, Node.js, and Ruby on Rails, among other frameworks and tools, resulting in a work-ready skillset.
      </p>
    </div>
  </div>
</div>

<!-- projects panel -->
<div class="col-md-6">
  <div class="panel panel-success">
    <div class="panel-heading">
      Projects
    </div>
    <div class="panel-body">
      <!-- mindkit -->
      <h4><%= link_to "MindKit", portfolio_mindkit_path %></h4>
      <h5><a href="https://github.com/apennell/mindKit">GitHub Repo</a></h5>
      <p>
        MindKit is a hybrid mobile app built with Ionic and AngularJS. The backend database is an API built with Node.js, Express, and PostgreSQL. It has a variety of tools for combating depression, namely the cognitive behavioral therapy automatic negative thought log, which guides the user through a series of questions using Ionic-Wizard, ultimately analyzing and tracking their improvement resulting from the exercise.
      </p>
      <br>
      <!-- create -->
      <h4><%= link_to "Create", portfolio_create_path %></h4>
      <h5><a href="https://createtoday.herokuapp.com/">Live Site</a> | <a href="https://github.com/apennell/create_app">GitHub Repo</a></h5>
      <p>
        Create is a daily art prompt web app built using JavaScript, Node.js, Express, and PostgreSQL, and integrating authentication and authorization. Utilizing Wordnik’s API, a new word appears every day to provide inspiration to create art, which can then be uploaded to a user’s account and viewed by anyone. 
      </p>
      <br>
      <!-- epoch -->
      <h4><%= link_to "Epoch", portfolio_epoch_path %></h4>
      <h5><a href="https://epochbank.herokuapp.com/">Live Site</a> | <a href="https://github.com/apennell/timebank">GitHub Repo</a></h5>
      <p>
        Epoch is a time banking web app built with Ruby on Rails, utilizing AJAX, Devise, and Twilio’s API. In addition to acting as project manager for three other engineers, my main tasks were authentication and authorization, constructing the User controller and views, and styling.
      </p>
    </div>
  </div>
</div>

<!-- work experience panel -->
<div class="col-md-6">
  <div class="panel panel-success">
    <div class="panel-heading">
      Work Experience
    </div>
    <div class="panel-body">
      <h4>Operations Associate</h4>
      <p>Twice | January to March 2015</p>
      <br>
      <h4>Fine Art Print Specialist</h4>
      <p>Lakeside Camera Photoworks | September 2012 - November 2014</p>
      <br>
      <h4>Freelance Photographer</h4>
      <p>Self-Employed | April 2012 to November 2014</p>
      <br>
      <h4>Assistant Manager</h4>
      <p>Langford Market | September 2011 to July 2012</p>
    </div>
  </div>
</div>

<div class="col-md-6">
  <br><br><br><br><br><br><br><br><br><br><br>
</div>

<!-- references panel -->
<!-- <div class="col-md-6 col-md-push-5 col-lg-6 col-lg-push-0">
  <div class="panel panel-success">
    <div class="panel-heading">
      References
    </div>
    <div class="panel-body">
      <p>Want to hear nice things employers and professors have had to say about me in the past? Check out them out in <a href="http://about-annie.divshot.io/">this about me page</a> that I made.</p>
    </div>
  </div>
  <br>
  <br>
  <br>
</div> -->

app/views/site/index.html.erb
<center><h1>hello world.</h1></center>
<center><h2>i'm annie.</h2></center>
<center><h3>i'm a full stack developer.</h3></center>
<center>
  <h4>
    i also really love design. this site is going to look great soon, trust me!<br>right now it's a work in progress, though.<br>get excited for something amazing, and in the meantime<br>explore the content and get to know me as a developer.
  </h4>
</center>
<br>
<center><a href="https://github.com/apennell"><i class="fa fa-github fa-2x"></i></a>
&nbsp; &nbsp;
<a href="https://www.linkedin.com/in/anniepennell"><i class="fa fa-linkedin fa-2x"></i></a>
&nbsp; &nbsp;
<a href="https://angel.co/annie-pennell"><i class="fa fa-angellist fa-2x"></i></a></center>

app/views/tiny_projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 port-index-header">
      <center>
        <h1>tiny projects</h1>
        <p>Not all apps need to be big. These are smaller apps and pages that I've made for fun and practice.</p>
      </center>
    </div>
  </div>
  
  <div class="row">
      <!-- About Me one page app -->
    <div class="col-xs-12 col-md-6">
      <h2>
        <a href="http://about-annie.divshot.io/">About Me</a>
      </h2>
      <a href="https://github.com/apennell/about_me_page"><strong>GitHub Repo</strong></a>
      <p>
        February 2015 | HTML, CSS, jQuery, AJAX<br>
        This static page was created as an application assignment for the General Assembly Web Development Immersive course.
      </p>
    </div>
    
      <!-- tic tac toe app -->
    <div class="col-xs-12 col-md-6">
      <h2>
        <a href="http://tictactoe-by-annie.divshot.io/">TicTacToe</a>
      </h2>
      <a href="https://github.com/apennell/tictactoe"><strong>GitHub Repo</strong></a>
      <p>
        March 2015 | JavaScript, jQuery, HTML, CSS<br>
        This TicTacToe project was my first venture into building a functioning app with JavaScript.
      </p>
    </div>
  </div>

  <br><br>
  
  <div class="well well-sm">
    <p><i class="fa fa-exclamation-triangle"></i> Don't worry—that's not all! I have many more tiny projects coming. In the meantime, you can check out my code on <strong><a href="https://github.com/apennell">GitHub</a></strong>.</p>
  </div>
</div>